version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: bbx_db
    environment:
      POSTGRES_DB: bbx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bbx"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: bbx_api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:app
      --host 0.0.0.0
      --port 8000"

volumes:
  dbdata: